### ISSUE TITLE
Erorr

### ISSUE THREAD

**Issue by YaNIND** [Refaltor77/CustomItem#4]
![IMG_20210629_112241](https://user-images.githubusercontent.com/84168756/123737128-9fbfb080-d8cc-11eb-94c7-bde393bbb82b.jpg)

**Comment by Willtom999** [comment]
Ok is this you have touched the code of the plugin ?

**Comment by Refaltor77** [comment]
Hey,I’m sorry I forgot to upload a file, worried solved!
