### ISSUE TITLE
Activate Custom Amor

### ISSUE THREAD

**Issue by AzaleeX** [Refaltor77/CustomItem#7]
more than one thing is missing for this plugin to be truly magical that we can load custom armor :)

**Comment by yangyong080228** [comment]
ye

**Comment by Willtom999** [comment]
soon

**Comment by Willtom999** [comment]
custom armor is disponible

**Comment by DretooFuni** [comment]
Use burger custom armor.

**Comment by Refaltor77** [comment]
https://github.com/Big-Potatoes/CustomItem
